name: ci master
on:
  push:
    branches:
      - "**"

jobs:
  ci-master: 
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v2
      - uses : actions/setup-node@v1
        with : 
          node-versions: '14'
      - uses : npm install
      - uses : npm run build
      - uses : npm run test
        env:
          CI: true