name: ci master
on:
  push:
    branches:
      - "master"

jobs:
  ci-master: 
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v2
      - uses : actions/setup-node@v1
        with : 
          node-versions: '14'
      - run : npm ci
      - run : npm run build
      - run : npm run test
      - uses : jamesives/github-pages-deploy-action@3.7.1
        env:
          CI: true